INSERT INTO TBL_SELLER (NAME,SALARY,BONUS,GENDER) 
VALUES ('Antonio',3500.50, 20.5, 1);

INSERT INTO TBL_SELLER (NAME,SALARY,BONUS,GENDER) 
VALUES ('Juliana',15000, 100, 0);

INSERT INTO TBL_SELLER (NAME,SALARY,BONUS,GENDER) 
VALUES ('Scalet',500, 0, 1);